version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: liquidity_db
    environment:
      POSTGRES_USER: liquidity
      POSTGRES_PASSWORD: liquiditypass
      POSTGRES_DB: liquidity
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U liquidity"]
      interval: 5s
      timeout: 5s
      retries: 10

  hunter:
    build: .
    container_name: liquidity_hunter
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    restart: unless-stopped
    command: ["python", "main.py"]

volumes:
  pgdata:
