version: '3.9'

services:
  app:
    build: .
    container_name: liquidity_hunter
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    depends_on:
      - db
    command: tail -f /dev/null  # para debug inicial

  db:
    image: postgres:14
    container_name: liquidity_db
    environment:
      POSTGRES_DB: hunter
      POSTGRES_USER: hunter_user
      POSTGRES_PASSWORD: hunter_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
